version: '3.7'

services:
  grafana:
    container_name: 'infinityPlugin'
    platform: "linux/amd64"
    build:
      context: ./.config
      args:
        grafana_image: ${GRAFANA_IMAGE:-grafana-enterprise}
        grafana_version: ${GRAFANA_VERSION:-10.0.3}
    ports:
      - 3001:3000
    volumes:
      - ./provisioning/dashboards-actual/:/dashboards/
      - ./provisioning:/etc/grafana/provisioning
      - ./dist/:/var/lib/grafana/plugins/yesoreyeram-infinity-datasource
    environment:
      - TERM=linux
      - GF_DEFAULT_APP_MODE=development
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=apofapof
      - GF_SECURITY_ANGULAR_SUPPORT_ENABLED=false
      - GF_SECURITY_CSRF_ALWAYS_CHECK=true
      - GF_ENTERPRISE_LICENSE_TEXT=${GF_ENTERPRISE_LICENSE_TEXT}
      - GF_FEATURE_TOGGLES_ENABLE=publicDashboards topnav dataConnectionsConsole newPanelChromeUI emptyDashboardPage correlations nestedFolders advancedDataSourcePicker
      - GF_PLUGIN_YESOREYERAM_INFINITY_DATASOURCE_TRACING=true
      - GF_INSTANCE_OTLP_ADDRESS=${GF_INSTANCE_OTLP_ADDRESS:-foo}
      - GF_INSTANCE_OTLP_PROPAGATION=${GF_INSTANCE_OTLP_PROPAGATION:-w3c}
